### 用 kernel SVM 機器學習,分類, 並未使用全部資料以及全部欄位

In [1]:
import numpy as np
import pandas as pd

In [2]:
import time

In [3]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
#做這個設定是為了讓dataframe可以顯示更多資料

In [4]:
data = pd.read_csv('usedCar_Dataset.csv')

In [5]:
data.head()

CarID MakeId                                              Title     BodyStyle Rental       Location GasMileage_city GasMileage_highway    Price   Mileage    Transmission  FuelType ExteriorColor InteriorColor DoorsNum MaximumSeating Engine         Drivetrain                VIN  OptionCount                                       MajorOptions Certified  Accident Check  OwnershipHistory  SellingDays  OriginPrice
0  100351603     m1                     2007 Chevrolet Tahoe - $11,999           suv    NaN    Garland, TX             NaN                NaN  11999.0  129280.0       Automatic  Gasoline          Gold           NaN      NaN            NaN     V8                NaN  1GNFC13J47R120389            0                                                NaN       NaN             0.0               2.0         1873      12999.0
1  101113873     m1                   2005 Chevrolet Express - $11,995           van    NaN  Claremont, NH             NaN                NaN  11995.0  118113.0       Automatic       NaN         White           NaN      NaN            NaN    NaN                NaN  1GBJG31U251136588            0                                                NaN       NaN             1.0               1.0         1863          NaN
2  102996725     m1  2010 Chevrolet Silverado 2500HD Work Truck Ext...  pickup_truck    NaN  Frankfort, KY             NaN                NaN  15900.0  144000.0       Automatic  Gasoline         White          Gray  4 doors        6 seats     V8   Four-Wheel Drive  1GC5KVBG7AZ218246            2                           Steel Wheels,Tow Package       NaN             0.0               2.0         1837      16900.0
3  103384798     m1  2014 Chevrolet Corvette Stingray 3LT Coupe RWD...         coupe    NaN  Lewistown, MT     17 MPG City     29 MPG Highway  49995.0    2500.0  7-Speed Manual  Gasoline           Red         Black  2 doors        2 seats     V8   Rear-Wheel Drive  1G1YE2D73E5104797            5  Bluetooth,Backup Camera,Aluminum Wheels,Naviga...       NaN             0.0               1.0         1832      62900.0
4  104800849     m1         2002 Chevrolet Monte Carlo SS FWD - $3,440         coupe    NaN    Delavan, IL     17 MPG City     27 MPG Highway   3440.0  174000.0       Automatic  Gasoline         Black         Black  2 doors        5 seats     V6  Front-Wheel Drive  2G1WX15K829249749            2                      Leather Seats,Aluminum Wheels       NaN             0.0               2.0         1809       4800.0

In [6]:
data.dtypes

CarID                   int64
MakeId                 object
Title                  object
BodyStyle              object
Rental                 object
Location               object
GasMileage_city        object
GasMileage_highway     object
Price                 float64
Mileage               float64
Transmission           object
FuelType               object
ExteriorColor          object
InteriorColor          object
DoorsNum               object
MaximumSeating         object
Engine                 object
Drivetrain             object
VIN                    object
OptionCount             int64
MajorOptions           object
Certified              object
Accident Check        float64
OwnershipHistory      float64
SellingDays             int64
OriginPrice           float64
dtype: object

In [7]:
data.columns

Index(['CarID', 'MakeId', 'Title', 'BodyStyle', 'Rental', 'Location', 'GasMileage_city', 'GasMileage_highway', 'Price', 'Mileage', 'Transmission', 'FuelType', 'ExteriorColor', 'InteriorColor', 'DoorsNum', 'MaximumSeating', 'Engine', 'Drivetrain', 'VIN', 'OptionCount', 'MajorOptions', 'Certified', 'Accident Check', 'OwnershipHistory', 'SellingDays', 'OriginPrice'], dtype='object')

In [8]:
# 在選擇欄位的時候,只選擇數字型欄位,如果是有包括文字的欄位就沒有加入

In [9]:
# 資料只使用了200筆,因為有些欄位當中可能有字串,還沒辦法直接進去訓練

In [10]:
X = data.iloc[:,[8,9,19,22,23,24,25]]

In [11]:
X.head(10)

Price   Mileage  OptionCount  Accident Check  OwnershipHistory  SellingDays  OriginPrice
0  11999.0  129280.0            0             0.0               2.0         1873      12999.0
1  11995.0  118113.0            0             1.0               1.0         1863          NaN
2  15900.0  144000.0            2             0.0               2.0         1837      16900.0
3  49995.0    2500.0            5             0.0               1.0         1832      62900.0
4   3440.0  174000.0            2             0.0               2.0         1809       4800.0
5   4890.0  115500.0            1             0.0               3.0         1809          NaN
6   4660.0  249000.0            3             0.0               3.0         1809          NaN
7   6550.0  188583.0            3             0.0               1.0         1809          NaN
8   9960.0   80124.0            4             0.0               2.0         1809      12740.0
9   9220.0  103000.0            4             0.0               1.0         1809          NaN

In [12]:
# X.iloc[:,:]

In [13]:
X.fillna(value=0, inplace=True)

c:\program files\python37\lib\site-packages\pandas\core\frame.py:4259: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  **kwargs


In [14]:
X.head(10)

Price   Mileage  OptionCount  Accident Check  OwnershipHistory  SellingDays  OriginPrice
0  11999.0  129280.0            0             0.0               2.0         1873      12999.0
1  11995.0  118113.0            0             1.0               1.0         1863          0.0
2  15900.0  144000.0            2             0.0               2.0         1837      16900.0
3  49995.0    2500.0            5             0.0               1.0         1832      62900.0
4   3440.0  174000.0            2             0.0               2.0         1809       4800.0
5   4890.0  115500.0            1             0.0               3.0         1809          0.0
6   4660.0  249000.0            3             0.0               3.0         1809          0.0
7   6550.0  188583.0            3             0.0               1.0         1809          0.0
8   9960.0   80124.0            4             0.0               2.0         1809      12740.0
9   9220.0  103000.0            4             0.0               1.0         1809          0.0

In [15]:
# X.astype('float32')

In [16]:
# X = X.where( X != 'unknown',0)

In [17]:
y = data.iloc[:,3]

In [18]:
y.fillna(value=0, inplace=True)

In [19]:
len(X) == len(y)

True

In [20]:
y.unique()

array(['suv', 'van', 'pickup_truck', 'coupe', 'crossover', 'sedan',
       'convertible', 'hatchback', 0, 'minivan', 'wagon'], dtype=object)

In [21]:
# y會有八種不同可能,也就是八種車型,會是一個分8類的問題
# Logistic Regression 原本是處理二元分類,不過可以用 OvR(One-vs.-Rest) 擴展成多元分類

In [22]:
y = y.where( y != 'coupe',1)
y = y.where( y != 'pickup_truck',2)
y = y.where( y != 'suv',3)
y = y.where( y != 'sedan',4)
y = y.where( y != 'convertible',5)
y = y.where( y != 'van',6)
y = y.where( y != 'crossover',7)
y = y.where( y != 'hatchback',8)
y = y.where( y != 'minivan',9)
y = y.where( y != 'wagon',10)

In [23]:
y.unique()

array([3, 6, 2, 1, 7, 4, 5, 8, 0, 9, 10], dtype=object)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=1, stratify=y)

In [26]:
X_train

Price   Mileage  OptionCount  Accident Check  OwnershipHistory  SellingDays  OriginPrice
2078932  38713.0   33125.0            5             0.0               1.0           42      38950.0
2345543  26990.0   15307.0            4             0.0               1.0          114      26991.0
1228556  33874.0   72920.0            6             0.0               2.0            5          0.0
1191794  28908.0   33365.0            5             1.0               1.0           36      29688.0
1481347  24795.0   70152.0            8             0.0               2.0           50      24995.0
...          ...       ...          ...             ...               ...          ...          ...
1887813  36575.0   39150.0            5             0.0               1.0           45      37995.0
1040859   6990.0  142444.0            0             0.0               6.0          130       7990.0
379743    4995.0  123025.0            2             1.0               5.0           40       5250.0
108051   37933.0   14770.0            3             0.0               1.0           66      38887.0
1155792  49630.0   70126.0            8             0.0               1.0          105      57217.0

[1662745 rows x 7 columns]

In [27]:
np.bincount(y_test)

array([   973,  28900, 125043,  79001, 202996,  13348,   9209, 195226,
        22282,  21132,  14495], dtype=int64)

In [28]:
np.bincount(y_train)

array([  2272,  67432, 291766, 184336, 473656,  31144,  21486, 455529,
        51993,  49308,  33823], dtype=int64)

In [29]:
# y_test = y_test.where( y != 'coupe',0)

In [30]:
# y_test = y_test.where( y != 'coupe',0)
# y_test = y_test.where( y != 'pickup_truck',1)
# y_test = y_test.where( y != 'suv',2)
# y_test = y_test.where( y != 'sedan',3)
# y_test = y_test.where( y != 'convertible',4)
# y_test = y_test.where( y != 'van',5)
# y_test = y_test.where( y != 'crossover',6)
# y_test = y_test.where( y != 'hatchback',7)

In [31]:
# 'coupe', 'pickup_truck', 'suv', 'sedan', 'convertible', 'van','crossover', 'hatchback'

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [34]:
np.dtype(y_train)
# dtype('O')

dtype('O')

In [35]:
# 在使用 Sklearn 的 Logistic Regression 時 , y的 type 必須 必須 要是 int
# 不要用 type() 確認 , 用 dtype 確認 ,如果是物件 'O' 要轉型別
y_train = y_train.astype('int')

In [36]:
np.dtype(y_train)
# 經過轉換後 ,變成 dtype('int32')

dtype('int32')

In [37]:
from sklearn.svm import SVC

In [38]:
svm = SVC(kernel='rbf', random_state=1, gamma=0.10, C=100.0)

In [ ]:
svm.fit(X_train_std, y_train)

In [ ]:
y_pred = svm.predict(X_test_std)

In [ ]:
accuracy = (y_pred == y_test).sum()/len(y_test)

In [ ]:
accuracy

In [ ]:
np.dtype(y_test)

In [ ]:
y_test = y_test.astype('int')

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)