### 用邏輯斯迴歸做機器學習,分類, 並未使用全部欄位

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
#做這個設定是為了讓dataframe可以顯示更多資料

In [3]:
data = pd.read_csv('usedCar_Dataset.csv')

In [4]:
data.head()

CarID MakeId                                              Title     BodyStyle Rental       Location GasMileage_city GasMileage_highway    Price   Mileage    Transmission  FuelType ExteriorColor InteriorColor DoorsNum MaximumSeating Engine         Drivetrain                VIN  OptionCount                                       MajorOptions Certified  Accident Check  OwnershipHistory  SellingDays  OriginPrice
0  100351603     m1                     2007 Chevrolet Tahoe - $11,999           suv    NaN    Garland, TX             NaN                NaN  11999.0  129280.0       Automatic  Gasoline          Gold           NaN      NaN            NaN     V8                NaN  1GNFC13J47R120389            0                                                NaN       NaN             0.0               2.0         1873      12999.0
1  101113873     m1                   2005 Chevrolet Express - $11,995           van    NaN  Claremont, NH             NaN                NaN  11995.0  118113.0       Automatic       NaN         White           NaN      NaN            NaN    NaN                NaN  1GBJG31U251136588            0                                                NaN       NaN             1.0               1.0         1863          NaN
2  102996725     m1  2010 Chevrolet Silverado 2500HD Work Truck Ext...  pickup_truck    NaN  Frankfort, KY             NaN                NaN  15900.0  144000.0       Automatic  Gasoline         White          Gray  4 doors        6 seats     V8   Four-Wheel Drive  1GC5KVBG7AZ218246            2                           Steel Wheels,Tow Package       NaN             0.0               2.0         1837      16900.0
3  103384798     m1  2014 Chevrolet Corvette Stingray 3LT Coupe RWD...         coupe    NaN  Lewistown, MT     17 MPG City     29 MPG Highway  49995.0    2500.0  7-Speed Manual  Gasoline           Red         Black  2 doors        2 seats     V8   Rear-Wheel Drive  1G1YE2D73E5104797            5  Bluetooth,Backup Camera,Aluminum Wheels,Naviga...       NaN             0.0               1.0         1832      62900.0
4  104800849     m1         2002 Chevrolet Monte Carlo SS FWD - $3,440         coupe    NaN    Delavan, IL     17 MPG City     27 MPG Highway   3440.0  174000.0       Automatic  Gasoline         Black         Black  2 doors        5 seats     V6  Front-Wheel Drive  2G1WX15K829249749            2                      Leather Seats,Aluminum Wheels       NaN             0.0               2.0         1809       4800.0

In [5]:
data.columns

Index(['CarID', 'MakeId', 'Title', 'BodyStyle', 'Rental', 'Location', 'GasMileage_city', 'GasMileage_highway', 'Price', 'Mileage', 'Transmission', 'FuelType', 'ExteriorColor', 'InteriorColor', 'DoorsNum', 'MaximumSeating', 'Engine', 'Drivetrain', 'VIN', 'OptionCount', 'MajorOptions', 'Certified', 'Accident Check', 'OwnershipHistory', 'SellingDays', 'OriginPrice'], dtype='object')

In [ ]:
# 在選擇欄位的時候,只選擇數字型欄位,如果是有包括文字的欄位就沒有加入

In [6]:
data.iloc[:,[8,9]]

Price   Mileage
0        11999.0  129280.0
1        11995.0  118113.0
2        15900.0  144000.0
3        49995.0    2500.0
4         3440.0  174000.0
...          ...       ...
2375345  15100.0       NaN
2375346      NaN       NaN
2375347      NaN       NaN
2375348      NaN       NaN
2375349      NaN       NaN

[2375350 rows x 2 columns]

In [7]:
data.iloc[:,16:]

Engine         Drivetrain                VIN  OptionCount                                       MajorOptions Certified  Accident Check  OwnershipHistory  SellingDays  OriginPrice
0           V8                NaN  1GNFC13J47R120389            0                                                NaN       NaN             0.0               2.0         1873      12999.0
1          NaN                NaN  1GBJG31U251136588            0                                                NaN       NaN             1.0               1.0         1863          NaN
2           V8   Four-Wheel Drive  1GC5KVBG7AZ218246            2                           Steel Wheels,Tow Package       NaN             0.0               2.0         1837      16900.0
3           V8   Rear-Wheel Drive  1G1YE2D73E5104797            5  Bluetooth,Backup Camera,Aluminum Wheels,Naviga...       NaN             0.0               1.0         1832      62900.0
4           V6  Front-Wheel Drive  2G1WX15K829249749            2                      Leather Seats,Aluminum Wheels       NaN             0.0               2.0         1809       4800.0
...        ...                ...                ...          ...                                                ...       ...             ...               ...          ...          ...
2375345     I4  Front-Wheel Drive  3C3CFFER3CT310225            0                                                NaN       NaN             0.0               1.0         1911      26350.0
2375346     I4  Front-Wheel Drive  3C3CFFBR8DT515920            0                                                NaN       NaN             0.0               3.0         1911          NaN
2375347     I4  Front-Wheel Drive  3C3CFFCR5CT310469            5  Leather Seats,Sunroof/Moonroof,Alloy Wheels,Bl...       NaN             0.0               1.0         1911          NaN
2375348     I4  Front-Wheel Drive  3C3CFFCR1DT693120            0                                                NaN       NaN             0.0               1.0         1911          NaN
2375349     I4  Front-Wheel Drive  3C3CFFBR5DT539107            0                                                NaN       NaN             0.0               3.0         1911          NaN

[2375350 rows x 10 columns]

In [8]:
data.iloc[:,[19,22,23,24,25]]

OptionCount  Accident Check  OwnershipHistory  SellingDays  OriginPrice
0                  0             0.0               2.0         1873      12999.0
1                  0             1.0               1.0         1863          NaN
2                  2             0.0               2.0         1837      16900.0
3                  5             0.0               1.0         1832      62900.0
4                  2             0.0               2.0         1809       4800.0
...              ...             ...               ...          ...          ...
2375345            0             0.0               1.0         1911      26350.0
2375346            0             0.0               3.0         1911          NaN
2375347            5             0.0               1.0         1911          NaN
2375348            0             0.0               1.0         1911          NaN
2375349            0             0.0               3.0         1911          NaN

[2375350 rows x 5 columns]

In [ ]:
# X = data.iloc[:,[8,9,19,22,23,24,25]]

In [ ]:
# 資料只使用了200筆,因為有些欄位當中可能有字串,還沒辦法直接進去訓練

In [16]:
X = data.iloc[:,[8,9,19,22,23,24,25]]

In [17]:
X.dtypes

Price               float64
Mileage             float64
OptionCount           int64
Accident Check      float64
OwnershipHistory    float64
SellingDays           int64
OriginPrice         float64
dtype: object

In [18]:
X = X.astype('float64')

In [19]:
X.dtypes

Price               float64
Mileage             float64
OptionCount         float64
Accident Check      float64
OwnershipHistory    float64
SellingDays         float64
OriginPrice         float64
dtype: object

In [20]:
X.head(10)

Price   Mileage  OptionCount  Accident Check  OwnershipHistory  SellingDays  OriginPrice
0  11999.0  129280.0          0.0             0.0               2.0       1873.0      12999.0
1  11995.0  118113.0          0.0             1.0               1.0       1863.0          NaN
2  15900.0  144000.0          2.0             0.0               2.0       1837.0      16900.0
3  49995.0    2500.0          5.0             0.0               1.0       1832.0      62900.0
4   3440.0  174000.0          2.0             0.0               2.0       1809.0       4800.0
5   4890.0  115500.0          1.0             0.0               3.0       1809.0          NaN
6   4660.0  249000.0          3.0             0.0               3.0       1809.0          NaN
7   6550.0  188583.0          3.0             0.0               1.0       1809.0          NaN
8   9960.0   80124.0          4.0             0.0               2.0       1809.0      12740.0
9   9220.0  103000.0          4.0             0.0               1.0       1809.0          NaN

In [ ]:
# X.iloc[0:200,:]

In [21]:
X.fillna(value=0, inplace=True)

In [22]:
X.head(10)

Price   Mileage  OptionCount  Accident Check  OwnershipHistory  SellingDays  OriginPrice
0  11999.0  129280.0          0.0             0.0               2.0       1873.0      12999.0
1  11995.0  118113.0          0.0             1.0               1.0       1863.0          0.0
2  15900.0  144000.0          2.0             0.0               2.0       1837.0      16900.0
3  49995.0    2500.0          5.0             0.0               1.0       1832.0      62900.0
4   3440.0  174000.0          2.0             0.0               2.0       1809.0       4800.0
5   4890.0  115500.0          1.0             0.0               3.0       1809.0          0.0
6   4660.0  249000.0          3.0             0.0               3.0       1809.0          0.0
7   6550.0  188583.0          3.0             0.0               1.0       1809.0          0.0
8   9960.0   80124.0          4.0             0.0               2.0       1809.0      12740.0
9   9220.0  103000.0          4.0             0.0               1.0       1809.0          0.0

In [ ]:
# X.astype('float32')

In [ ]:
# X = X.where( X != 'unknown',0)

In [23]:
y = data.iloc[:,3]

In [24]:
y.fillna(value=0, inplace=True)

In [25]:
len(X) == len(y)

True

In [26]:
y.unique()

array(['suv', 'van', 'pickup_truck', 'coupe', 'crossover', 'sedan',
       'convertible', 'hatchback', 0, 'minivan', 'wagon'], dtype=object)

In [ ]:
# y會有八種不同可能,也就是八種車型,會是一個分8類的問題
# Logistic Regression 原本是處理二元分類,不過可以用 OvR(One-vs.-Rest) 擴展成多元分類

In [27]:
y = y.where( y != 'coupe',1)
y = y.where( y != 'pickup_truck',2)
y = y.where( y != 'suv',3)
y = y.where( y != 'sedan',4)
y = y.where( y != 'convertible',5)
y = y.where( y != 'van',6)
y = y.where( y != 'crossover',7)
y = y.where( y != 'hatchback',8)
y = y.where( y != 'minivan',9)
y = y.where( y != 'wagon',10)

In [28]:
y.unique()

array([3, 6, 2, 1, 7, 4, 5, 8, 0, 9, 10], dtype=object)

In [29]:
# y.astype('int')

0          3
1          6
2          2
3          1
4          1
          ..
2375345    5
2375346    8
2375347    8
2375348    8
2375349    8
Name: BodyStyle, Length: 2375350, dtype: int32

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=1, stratify=y)

In [32]:
X_train

Price   Mileage  OptionCount  Accident Check  OwnershipHistory  SellingDays  OriginPrice
2078932  38713.0   33125.0          5.0             0.0               1.0         42.0      38950.0
2345543  26990.0   15307.0          4.0             0.0               1.0        114.0      26991.0
1228556  33874.0   72920.0          6.0             0.0               2.0          5.0          0.0
1191794  28908.0   33365.0          5.0             1.0               1.0         36.0      29688.0
1481347  24795.0   70152.0          8.0             0.0               2.0         50.0      24995.0
...          ...       ...          ...             ...               ...          ...          ...
1887813  36575.0   39150.0          5.0             0.0               1.0         45.0      37995.0
1040859   6990.0  142444.0          0.0             0.0               6.0        130.0       7990.0
379743    4995.0  123025.0          2.0             1.0               5.0         40.0       5250.0
108051   37933.0   14770.0          3.0             0.0               1.0         66.0      38887.0
1155792  49630.0   70126.0          8.0             0.0               1.0        105.0      57217.0

[1662745 rows x 7 columns]

In [33]:
np.bincount(y_test)

array([   973,  28900, 125043,  79001, 202996,  13348,   9209, 195226,
        22282,  21132,  14495], dtype=int64)

In [34]:
np.bincount(y_train)

array([  2272,  67432, 291766, 184336, 473656,  31144,  21486, 455529,
        51993,  49308,  33823], dtype=int64)

In [ ]:
# y_test = y_test.where( y != 'coupe',0)

In [ ]:
# y_test = y_test.where( y != 'coupe',0)
# y_test = y_test.where( y != 'pickup_truck',1)
# y_test = y_test.where( y != 'suv',2)
# y_test = y_test.where( y != 'sedan',3)
# y_test = y_test.where( y != 'convertible',4)
# y_test = y_test.where( y != 'van',5)
# y_test = y_test.where( y != 'crossover',6)
# y_test = y_test.where( y != 'hatchback',7)

In [ ]:
# 'coupe', 'pickup_truck', 'suv', 'sedan', 'convertible', 'van','crossover', 'hatchback'

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [ ]:
# y_train[:]

In [37]:
np.dtype(y_train)
# dtype('O')

dtype('O')

In [38]:
# 在使用 Sklearn 的 Logistic Regression 時 , y的 type 必須 必須 要是 int
# 不要用 type() 確認 , 用 dtype 確認 ,如果是物件 'O' 要轉型別
y_train = y_train.astype('int')

In [39]:
np.dtype(y_train)
# 經過轉換後 ,變成 dtype('int32')

dtype('int32')

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
lr = LogisticRegression(C=100.0, random_state=1)
lr.fit(X_train_std, y_train)

c:\program files\python37\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\program files\python37\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=100.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=1, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [42]:
lr.predict(X_test_std)

array([4, 4, 4, ..., 4, 7, 4])

In [43]:
lr.predict_proba(X_test_std)

array([[0.00046475, 0.04235896, 0.1507854 , ..., 0.05059679, 0.03787881,
        0.02833317],
       [0.00089214, 0.05408645, 0.10000631, ..., 0.03698903, 0.02618407,
        0.02212154],
       [0.00345214, 0.01661155, 0.12948969, ..., 0.07200682, 0.04333671,
        0.03083296],
       ...,
       [0.00141981, 0.05080511, 0.13568512, ..., 0.04188877, 0.02775669,
        0.02435001],
       [0.00033153, 0.04416057, 0.29560019, ..., 0.00464802, 0.01896933,
        0.00973179],
       [0.00067391, 0.02228906, 0.14228731, ..., 0.02393273, 0.03876887,
        0.01927974]])

In [44]:
lr.predict_proba(X_test_std[:3,:]) #因為分類分11種,所以會輸出可能是這11種類別的個別機率

array([[0.00046475, 0.04235896, 0.1507854 , 0.10769289, 0.3635247 ,
        0.02198455, 0.01597479, 0.18040519, 0.05059679, 0.03787881,
        0.02833317],
       [0.00089214, 0.05408645, 0.10000631, 0.07672488, 0.38778577,
        0.02349906, 0.01320223, 0.2585085 , 0.03698903, 0.02618407,
        0.02212154],
       [0.00345214, 0.01661155, 0.12948969, 0.055191  , 0.34482903,
        0.00648324, 0.03584761, 0.26191926, 0.07200682, 0.04333671,
        0.03083296]])

In [45]:
y_pred = lr.predict(X_test_std)

In [46]:
accuracy = (y_pred == y_test).sum()/len(y_test)

In [47]:
accuracy

0.40310129735267086