In [1]:
import numpy as np
import pandas as pd

In [2]:
%%time
data = pd.read_csv('usedCar_Dataset_0206.csv')

Wall time: 8.62 s


In [86]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

-----------------------------------------------------

In [3]:
data.shape

(2375350, 30)

In [4]:
data.columns

Index(['CarID', 'MakeId', 'Title', 'Year', 'Make', 'Model', 'Trim',
       'BodyStyle', 'Rental', 'Location', 'GasMileage_city',
       'GasMileage_highway', 'Price', 'Mileage', 'Transmission', 'FuelType',
       'ExteriorColor', 'InteriorColor', 'DoorsNum', 'MaximumSeating',
       'Engine', 'Drivetrain', 'VIN', 'OptionCount', 'MajorOptions',
       'Certified', 'Accident Check', 'OwnershipHistory', 'SellingDays',
       'OriginPrice'],
      dtype='object')

In [5]:
data.head(5)

CarID MakeId                                              Title  Year  \
0  100351603     m1                     2007 Chevrolet Tahoe - $11,999  2007   
1  101113873     m1                   2005 Chevrolet Express - $11,995  2005   
2  102996725     m1  2010 Chevrolet Silverado 2500HD Work Truck Ext...  2010   
3  103384798     m1  2014 Chevrolet Corvette Stingray 3LT Coupe RWD...  2014   
4  104800849     m1         2002 Chevrolet Monte Carlo SS FWD - $3,440  2002   

        Make             Model                            Trim     BodyStyle  \
0  Chevrolet             Tahoe                             NaN           suv   
1  Chevrolet           Express                             NaN           van   
2  Chevrolet  Silverado 2500HD  Work Truck Extended Cab LB 4WD  pickup_truck   
3  Chevrolet          Corvette          Stingray 3LT Coupe RWD         coupe   
4  Chevrolet       Monte Carlo                          SS FWD         coupe   

  Rental       Location  ... Engine         Drivetrain                VIN  \
0    NaN    Garland, TX  ...     V8                NaN  1GNFC13J47R120389   
1    NaN  Claremont, NH  ...    NaN                NaN  1GBJG31U251136588   
2    NaN  Frankfort, KY  ...     V8   Four-Wheel Drive  1GC5KVBG7AZ218246   
3    NaN  Lewistown, MT  ...     V8   Rear-Wheel Drive  1G1YE2D73E5104797   
4    NaN    Delavan, IL  ...     V6  Front-Wheel Drive  2G1WX15K829249749   

   OptionCount                                       MajorOptions Certified  \
0            0                                                NaN       NaN   
1            0                                                NaN       NaN   
2            2                           Steel Wheels,Tow Package       NaN   
3            5  Bluetooth,Backup Camera,Aluminum Wheels,Naviga...       NaN   
4            2                      Leather Seats,Aluminum Wheels       NaN   

  Accident Check OwnershipHistory SellingDays OriginPrice  
0            0.0              2.0        1873     12999.0  
1            1.0              1.0        1863         NaN  
2            0.0              2.0        1837     16900.0  
3            0.0              1.0        1832     62900.0  
4            0.0              2.0        1809      4800.0  

[5 rows x 30 columns]

In [6]:
data.groupby(by='MakeId').size().sort_values(ascending=False)

MakeId
m2      329590
m1      293079
m7      192976
m12     167186
m32     138695
m6      122921
m24     106549
m26      99698
m28      96737
m3       78226
m191     76643
m43      72802
m33      68444
m55      58642
m37      49712
m53      48757
m19      40281
m23      38940
m22      37894
m21      35364
m42      32988
m84      28800
m4       24941
m38      21555
m48      15158
m35      14283
m46      13522
m56      13177
m45      10680
m31       6989
m47       6474
m52       4682
m98       4135
m44       3307
m51       3205
m40       2774
m27       2110
m25       1870
m20       1596
m124      1249
m203      1146
m112      1144
m54        917
m50        872
m85        799
m34        691
m110       639
m49        629
m111       610
m141       483
m87        405
m30        249
m135        94
m194        40
m79          1
dtype: int64

---------------------------------------------------------------------------

In [7]:
car_m54 = data[data['MakeId'] == 'm54']

In [8]:
car_m54.shape

(917, 30)

In [10]:
car_m54 = car_m54.dropna(subset=['Price', 'Mileage', 'Accident Check', 'OwnershipHistory'])

In [11]:
car_m54.shape

(787, 30)

In [12]:
car_m54.dtypes

CarID                   int64
MakeId                 object
Title                  object
Year                    int64
Make                   object
Model                  object
Trim                   object
BodyStyle              object
Rental                 object
Location               object
GasMileage_city        object
GasMileage_highway     object
Price                 float64
Mileage               float64
Transmission           object
FuelType               object
ExteriorColor          object
InteriorColor          object
DoorsNum               object
MaximumSeating         object
Engine                 object
Drivetrain             object
VIN                    object
OptionCount             int64
MajorOptions           object
Certified              object
Accident Check        float64
OwnershipHistory      float64
SellingDays             int64
OriginPrice           float64
dtype: object

In [13]:
train_data = car_m54.iloc[:,[3,12,13,23,26,27,28,29]]

In [14]:
train_data.isnull().sum()

Year                  0
Price                 0
Mileage               0
OptionCount           0
Accident Check        0
OwnershipHistory      0
SellingDays           0
OriginPrice         503
dtype: int64

In [15]:
train_data.shape

(787, 8)

In [16]:
train_data = train_data.drop(columns=['OriginPrice'])

In [17]:
train_data.shape

(787, 7)

In [18]:
train_data.isnull().sum()

Year                0
Price               0
Mileage             0
OptionCount         0
Accident Check      0
OwnershipHistory    0
SellingDays         0
dtype: int64

In [19]:
train_data.head(5)

Year   Price   Mileage  OptionCount  Accident Check  \
1952578  2007  2977.0  157928.0            0             1.0   
1952579  2003  3500.0  163000.0            0             2.0   
1952581  2010  5999.0   90915.0            0             1.0   
1952587  2004  2750.0  117806.0            1             1.0   
1952589  2007  6750.0   74729.0            2             0.0   

         OwnershipHistory  SellingDays  
1952578               2.0         1830  
1952579               4.0         1431  
1952581               2.0         1312  
1952587               2.0         1139  
1952589               3.0         1050

In [20]:
from sklearn.preprocessing import MinMaxScaler

In [21]:
mms = MinMaxScaler()

In [22]:
train_data.iloc[:,:] = mms.fit_transform(train_data.iloc[:,:])

In [23]:
train_data.head()

Year     Price   Mileage  OptionCount  Accident Check  \
1952578  0.777778  0.019348  0.596435        0.000            0.25   
1952579  0.629630  0.023605  0.615602        0.000            0.50   
1952581  0.888889  0.043946  0.343192        0.000            0.25   
1952587  0.666667  0.017500  0.444813        0.125            0.25   
1952589  0.777778  0.050059  0.282024        0.250            0.00   

         OwnershipHistory  SellingDays  
1952578               0.1     0.874343  
1952579               0.3     0.683708  
1952581               0.1     0.626851  
1952587               0.1     0.544195  
1952589               0.2     0.501672

In [24]:
train_data.shape

(787, 7)

----------------------------------------------------------------------------------------

In [25]:
from sklearn.cluster import OPTICS

In [26]:
opt = OPTICS(min_samples=5,
    max_eps=0.2,
    metric='minkowski',
    p=2,
    cluster_method='xi',
    eps=None,
    xi=0.05,
    leaf_size=30,
    n_jobs=6)

In [27]:
%%time
y_opt = opt.fit_predict(train_data)

Wall time: 1min 14s


In [28]:
np.unique(y_opt)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [30]:
y_cluster = y_opt[y_opt >= 0]

In [31]:
np.bincount(y_cluster)

array([ 7,  7,  6,  5,  6,  7,  8,  8,  8, 11,  9,  6,  5,  9,  9,  7, 11,
       10, 15,  7,  5,  5,  6,  6,  5,  7,  6,  6,  5,  6, 10,  9],
      dtype=int64)

In [32]:
from sklearn.cluster import DBSCAN

In [73]:
db = DBSCAN(eps=0.2,
    min_samples=5,
    metric='euclidean',
    n_jobs=6)

In [74]:
%%time
y_db = db.fit_predict(train_data)

Wall time: 110 ms


In [75]:
np.unique(y_db)

array([-1,  0,  1,  2,  3], dtype=int64)

In [76]:
y_cluster_db = y_db[y_db >= 0]

In [77]:
np.bincount(y_cluster_db)

array([562, 144,  22,   5], dtype=int64)

In [78]:
car_m54.shape

(787, 30)

In [79]:
len(y_opt)

787

In [80]:
len(y_db)

787

In [81]:
car_m54['labels_opt'] = y_opt

In [82]:
car_m54['labels_db'] = y_db

In [88]:
car_m54[car_m54['labels_opt'] == 3]

CarID MakeId                                     Title  Year    Make    Model          Trim BodyStyle Rental            Location GasMileage_city GasMileage_highway   Price   Mileage       Transmission  FuelType ExteriorColor InteriorColor DoorsNum MaximumSeating Engine         Drivetrain                VIN  OptionCount      MajorOptions Certified  Accident Check  OwnershipHistory  SellingDays  OriginPrice  labels_opt  labels_db
1952660  238745222    m54      2004 Suzuki XL-7 EX III 4WD - $3,995  2004  Suzuki     XL-7    EX III 4WD       suv    NaN     Murphysboro, IL     15 MPG City     20 MPG Highway  3995.0  131800.0  5-Speed Automatic  Gasoline        Silver          Gray  4 doors        7 seats     V6   Four-Wheel Drive  JS3TX92VX44113055            1  Sunroof/Moonroof       NaN             0.0               2.0          245       4995.0           3          0
1952739  247692203    m54      2005 Suzuki Forenza S Sedan - $2,370  2005  Suzuki  Forenza       S Sedan     sedan    NaN     Mooresville, IN             NaN                NaN  2370.0  125217.0  5-Speed Automatic  Gasoline           Red          Gray  4 doors        5 seats     I4  Front-Wheel Drive  KL5JD56Z75K115854            1      Steel Wheels       NaN             0.0               2.0          150          NaN           3          0
1952741  247794090    m54     2003 Suzuki XL-7 Limited 4WD - $2,900  2003  Suzuki     XL-7   Limited 4WD       suv    NaN  Fredericksburg, VA     15 MPG City     18 MPG Highway  2900.0  137831.0          Automatic  Gasoline         White           NaN  4 doors        7 seats     V6   Four-Wheel Drive  JS3TX92VX34101504            1      Alloy Wheels       NaN             0.0               2.0          148       3499.0           3          0
1952762  249061807    m54  2004 Suzuki Verona 4 Dr S Sedan - $2,550  2004  Suzuki   Verona  4 Dr S Sedan     sedan    NaN        Republic, MO     17 MPG City     25 MPG Highway  2550.0  136811.0          Automatic  Gasoline          Blue         Black  4 doors        5 seats     I6  Front-Wheel Drive  KL5VJ52L64B110641            1      Steel Wheels       NaN             0.0               2.0          136          NaN           3          0
1952918  255648093    m54          2005 Suzuki XL-7 LX 4WD - $4,488  2005  Suzuki     XL-7        LX 4WD       suv    NaN       Johnstown, PA     15 MPG City     20 MPG Highway  4488.0  129000.0  5-Speed Automatic  Gasoline         Black   Brown (Tan)  4 doors        5 seats     V6   Four-Wheel Drive  JS3TX92V254100799            1      Alloy Wheels       NaN             0.0               2.0           67       4288.0           3          0

-----------------------------------------------------

In [89]:
opt2 = OPTICS(min_samples=5,
    max_eps=0.2,
    metric='minkowski',
    p=2,
    cluster_method='dbscan',
    eps=0.2,
    leaf_size=30,
    n_jobs=6)

In [90]:
%%time
y_opt2 = opt2.fit_predict(train_data)

Wall time: 1min 15s


In [91]:
np.unique(y_opt2)

array([-1,  0,  1,  2,  3])

In [92]:
y_cluster_opt2 = y_opt2[y_opt2 >= 0]

In [93]:
np.bincount(y_cluster_opt2)

array([561, 142,  22,   4], dtype=int64)

------------------------------------------------------------------------------

---------------------------------------------------------

In [94]:
car_m45 = data[data['MakeId'] == 'm45']

In [95]:
car_m45.shape

(10680, 30)

In [96]:
car_m45 = car_m45.dropna(subset=['Price', 'Mileage', 'Accident Check', 'OwnershipHistory'])

In [97]:
car_m45.shape

(9633, 30)

In [98]:
car_m45.dtypes

CarID                   int64
MakeId                 object
Title                  object
Year                    int64
Make                   object
Model                  object
Trim                   object
BodyStyle              object
Rental                 object
Location               object
GasMileage_city        object
GasMileage_highway     object
Price                 float64
Mileage               float64
Transmission           object
FuelType               object
ExteriorColor          object
InteriorColor          object
DoorsNum               object
MaximumSeating         object
Engine                 object
Drivetrain             object
VIN                    object
OptionCount             int64
MajorOptions           object
Certified              object
Accident Check        float64
OwnershipHistory      float64
SellingDays             int64
OriginPrice           float64
dtype: object

In [101]:
train_data2 = car_m45.iloc[:,[3,12,13,23,26,27,28]]

In [102]:
train_data2.isnull().sum()

Year                0
Price               0
Mileage             0
OptionCount         0
Accident Check      0
OwnershipHistory    0
SellingDays         0
dtype: int64

In [105]:
train_data2.shape

(9633, 7)

In [106]:
train_data2.head(5)

Year   Price   Mileage  OptionCount  Accident Check  OwnershipHistory  SellingDays
1848599  2010  6895.0  111871.0            1             0.0               1.0         1727
1848600  2007  7995.0   64415.0            1             0.0               5.0         1421
1848601  2008  7998.0   29731.0            1             2.0               1.0         1362
1848602  2002  4995.0  155985.0            0             0.0               6.0         1187
1848604  2003  3795.0  114701.0            0             0.0               3.0         1153

In [107]:
mms = MinMaxScaler()

In [108]:
train_data2.iloc[:,:] = mms.fit_transform(train_data2.iloc[:,:])

c:\program files\python37\lib\site-packages\pandas\core\indexing.py:494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [109]:
train_data2.head()

Year     Price   Mileage  OptionCount  Accident Check  OwnershipHistory  SellingDays
1848599  0.444444  0.040342  0.433797         0.05             0.0               0.0     0.771326
1848600  0.277778  0.049399  0.249687         0.05             0.0               0.4     0.634658
1848601  0.333333  0.049423  0.115127         0.05             0.5               0.0     0.608307
1848602  0.000000  0.024699  0.604941         0.00             0.0               0.5     0.530147
1848604  0.055556  0.014820  0.444776         0.00             0.0               0.2     0.514962

In [111]:
train_data2.shape

(9633, 7)

In [112]:
opt_2 = OPTICS(min_samples=5,
    max_eps=0.2,
    metric='minkowski',
    p=2,
    cluster_method='xi',
    eps=None,
    xi=0.05,
    leaf_size=30,
    n_jobs=6)

In [113]:
%%time
y_opt_2 = opt_2.fit_predict(train_data2)

Wall time: 17min 40s


In [114]:
np.unique(y_opt_2)

array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
        25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
       168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 17

In [115]:
y_cluster_opt_2 = y_opt_2[y_opt_2 >= 0]

In [116]:
np.bincount(y_cluster_opt_2)

array([ 6,  6,  5,  9,  5,  6,  7,  5,  5, 13,  8,  5, 11, 11, 11,  6,  8,
        7,  7, 18,  9,  9,  5, 17, 12,  8, 10,  7,  7,  8, 15,  5,  9, 12,
        5,  6,  5,  6,  6, 10,  9,  8,  6,  6, 11,  5, 14,  8, 14, 14,  7,
        5,  5,  8, 15,  5,  5, 12,  5, 11,  8, 19, 10, 13, 22, 17,  6,  5,
       11,  7, 11, 19, 16, 14, 11,  5,  8, 31,  8,  5, 13,  7,  8, 13, 23,
       16,  8,  7,  6,  8, 12, 14, 10, 14,  7, 10, 10,  6,  5,  8,  5,  5,
        6,  9, 15,  6, 12,  5, 14,  9, 16, 14,  6,  6,  5,  8,  8,  6,  5,
        5,  9, 10,  8,  7, 13,  6,  7,  9,  7,  6,  6,  5, 21, 18,  6,  5,
       12,  5,  9,  5, 28,  6,  5,  7,  7,  7, 10,  9, 18, 10,  7, 10, 12,
       10,  6,  6,  5, 10,  5,  6, 15,  7, 11, 12,  9,  8,  6,  5, 13,  5,
        6,  9,  9,  5,  7,  7, 18,  5,  8,  8,  8,  9,  5, 15,  9,  5,  8,
        5, 14,  6,  7,  5, 11,  5,  5,  8, 22,  9,  5,  8,  9, 12,  8,  5,
        5,  5,  5,  8,  9, 13,  8,  5,  5,  5,  5,  7,  5,  7,  6, 18,  5,
        8, 15,  5,  5, 13

In [117]:
db = DBSCAN(eps=0.2,
    min_samples=5,
    metric='euclidean',
    n_jobs=6)

In [118]:
%%time
y_db2 = db.fit_predict(train_data2)

Wall time: 597 ms


In [119]:
np.unique(y_db2)

array([-1,  0,  1,  2,  3], dtype=int64)

In [120]:
y_cluster_db2 = y_db2[y_db2 >= 0]

In [121]:
np.bincount(y_cluster_db2)

array([8155, 1225,  179,   11], dtype=int64)

In [122]:
opt_3 = OPTICS(min_samples=10,
    max_eps=0.2,
    metric='minkowski',
    p=2,
    cluster_method='xi',
    eps=None,
    xi=0.05,
    leaf_size=30,
    n_jobs=6)

In [123]:
%%time
y_opt_3 = opt_3.fit_predict(train_data2)

Wall time: 17min 30s


In [124]:
np.unique(y_opt_3)

array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
        25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102])

In [125]:
y_cluster_opt_3 = y_opt_3[y_opt_3 >= 0]

In [126]:
np.bincount(y_cluster_opt_3)

array([ 11,  21,  16,  19,  23,  17,  11,  23,  12,  12,  19,  11,  19,
        18,  30,  26,  27,  50,  10,  12,  20,  18,  35,  10,  13,  24,
        10,  13,  12,  14,  24,  27,  11,  20,  11, 238, 146, 190,  14,
        21,  11,  21,  75,  31,  29,  45,  19,  44,  11,  14,  11,  20,
        10,  22,  10,  29,  22,  13,  15,  29,  12,  14,  14,  28,  17,
        14,  21,  13,  49,  13,  13,  19,  18,  13,  10,  14,  11,  17,
        31,  12,  13,  14,  31,  14,  13,  17,  11,  16,  27,  13,  13,
        13,  10,  10,  31,  14,  10,  18,  15,  11,  41,  20,  16],
      dtype=int64)

----------------------------------------------------------------------------------

In [127]:
opt_4 = OPTICS(min_samples=20,
    max_eps=0.2,
    metric='minkowski',
    p=2,
    cluster_method='xi',
    eps=None,
    xi=0.05,
    leaf_size=30,
    n_jobs=6)

In [128]:
%%time
y_opt_4 = opt_4.fit_predict(train_data2)

Wall time: 17min 12s


In [129]:
np.unique(y_opt_4)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34])

In [130]:
y_cluster_opt_4 = y_opt_4[y_opt_4 >= 0]

In [131]:
np.bincount(y_cluster_opt_4)

array([  67,   23,   29,   68,   46,  120,   47,   40,   48,  127,   21,
         80,   33,   32,   25,  106,   32,  237,  139,  187,   20,  135,
         81,   51,   46,   22,   36,   38,   66,   34,   38,   29,   26,
       1194,  150], dtype=int64)