In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('final_data.csv')

In [3]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [4]:
data.head(3)

Price   Mileage  DoorsNum  MaximumSeating  Accident Check  OwnershipHistory  SellingDays  OriginPrice  Median Household Income(USD)  Income Ranking  Cost Ranking   Density       Pop  LandArea  Vehicle Count  Location_AL  Location_AR  Location_AZ  Location_CA  Location_CO  Location_CT  Location_DC  Location_DE  Location_FL  Location_GA  Location_IA  Location_ID  Location_IL  Location_IN  Location_KS  Location_KY  Location_LA  Location_MA  Location_MD  Location_ME  Location_MI  Location_MN  Location_MO  Location_MS  Location_MT  Location_NC  Location_ND  Location_NE  Location_NH  Location_NJ  Location_NM  Location_NV  Location_NY  Location_OH  Location_OK  Location_OR  Location_PA  Location_SC  Location_SD  Location_TN  Location_TX  Location_UT  Location_VA  Location_VT  Location_WA  Location_WI  Location_WV  Location_WY  BodyStyle_convertible  BodyStyle_coupe  BodyStyle_crossover  BodyStyle_hatchback  BodyStyle_minivan  BodyStyle_pickup_truck  BodyStyle_sedan  BodyStyle_suv  \
0  11999.0  129280.0       4.0             5.0             0.0               2.0         1873      12999.0                       59570.0              21             9  111.3457  29087070    261232         199688            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            1            0            0            0            0            0            0            0                      0                0                    0                    0                  0                       0                0              1   
1  34999.0   21806.0       2.0             2.0             0.0               3.0         1690      37000.0                       59570.0              21             9  111.3457  29087070    261232         199688            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            1            0            0            0            0            0            0            0                      0                1                    0                    0                  0                       0                0              0   
2  39995.0   14170.0       4.0             4.0             0.0               1.0         1506      24995.0                       59570.0              21             9  111.3457  29087070    261232         199688            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            1            0            0            0            0            0            0            0                      0                0                    0                    1                  0                       0                0              0   

   BodyStyle_van  Bo

In [5]:
data.columns

Index(['Price', 'Mileage', 'DoorsNum', 'MaximumSeating', 'Accident Check', 'OwnershipHistory', 'SellingDays', 'OriginPrice', 'Median Household Income(USD)', 'Income Ranking',
       ...
       'Engine_V12', 'Engine_V6', 'Engine_V8', 'Engine_W12', 'Engine_W8', 'Drivetrain_4X2', 'Drivetrain_All-Wheel Drive', 'Drivetrain_Four-Wheel Drive', 'Drivetrain_Front-Wheel Drive', 'Drivetrain_Rear-Wheel Drive'], dtype='object', length=104)

In [6]:
columns_need_std =['Price',
                   'Mileage',
                   'SellingDays','OriginPrice','Median Household Income(USD)','Density','Pop','LandArea','Vehicle Count']

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
std = StandardScaler()

In [9]:
std.fit_transform(data[columns_need_std])

array([[-0.47096102,  1.3464497 , 17.43617285, ...,  1.3986411 ,
         2.73685775,  1.69846881],
       [ 0.77828868, -0.83425379, 15.66301746, ...,  1.3986411 ,
         2.73685775,  1.69846881],
       [ 1.04964744, -0.98919221, 13.88017269, ...,  1.3986411 ,
         2.73685775,  1.69846881],
       ...,
       [-0.62298928, -0.15058496, -0.71202415, ..., -1.15852495,
        -1.18771629, -1.48767581],
       [ 0.01793013, -0.05927762, -0.11128298, ..., -1.15852495,
        -1.18771629, -1.48767581],
       [-0.3622763 , -0.28247335, -0.5860623 , ..., -1.15852495,
        -1.18771629, -1.48767581]])

In [10]:
data[columns_need_std] = std.fit_transform(data[columns_need_std])

In [11]:
data.head(10)

Price   Mileage  DoorsNum  MaximumSeating  Accident Check  OwnershipHistory  SellingDays  OriginPrice  Median Household Income(USD)  Income Ranking  Cost Ranking   Density       Pop  LandArea  Vehicle Count  Location_AL  Location_AR  Location_AZ  Location_CA  Location_CO  Location_CT  Location_DC  Location_DE  Location_FL  Location_GA  Location_IA  Location_ID  Location_IL  Location_IN  Location_KS  Location_KY  Location_LA  Location_MA  Location_MD  Location_ME  Location_MI  Location_MN  Location_MO  Location_MS  Location_MT  Location_NC  Location_ND  Location_NE  Location_NH  Location_NJ  Location_NM  Location_NV  Location_NY  Location_OH  Location_OK  Location_OR  Location_PA  Location_SC  Location_SD  Location_TN  Location_TX  Location_UT  Location_VA  Location_VT  Location_WA  Location_WI  Location_WV  Location_WY  BodyStyle_convertible  BodyStyle_coupe  BodyStyle_crossover  BodyStyle_hatchback  BodyStyle_minivan  BodyStyle_pickup_truck  BodyStyle_sedan  BodyStyle_suv  \
0  -0.470961  1.346450       4.0             5.0             0.0               2.0    17.436173    -0.001908                     -0.149268              21             9 -0.559127  1.398641  2.736858       1.698469            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            1            0            0            0            0            0            0            0                      0                0                    0                    0                  0                       0                0              1   
1   0.778289 -0.834254       2.0             2.0             0.0               3.0    15.663017     0.001538                     -0.149268              21             9 -0.559127  1.398641  2.736858       1.698469            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            1            0            0            0            0            0            0            0                      0                1                    0                    0                  0                       0                0              0   
2   1.049647 -0.989192       4.0             4.0             0.0               1.0    13.880173    -0.000185                     -0.149268              21             9 -0.559127  1.398641  2.736858       1.698469            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            0            1            0            0            0            0            0            0            0                      0                0                    0                    1                  0                       0                0              0   
3   1.891805 -1

In [12]:
from sklearn.cluster import DBSCAN

In [13]:
db = DBSCAN(eps=0.2, min_samples=10, metric='euclidean')

In [14]:
y_db = db.fit_predict(data)

In [15]:
y_db

array([-1, -1, -1, ..., -1, -1, -1], dtype=int64)

In [16]:
np.unique(y_db)

array([  -1,    0,    1, ..., 5528, 5529, 5530], dtype=int64)

In [17]:
labels = db.labels_

In [18]:
np.unique(labels)

array([  -1,    0,    1, ..., 5528, 5529, 5530], dtype=int64)

In [19]:
len(db.components_[0])

104

In [20]:
len(data.columns)

104

In [21]:
data2 = data

In [22]:
data2['labels'] = labels

In [23]:
data2.iloc[:,[0,1,-1]]

Price   Mileage  labels
0       -0.470961  1.346450      -1
1        0.778289 -0.834254      -1
2        1.049647 -0.989192      -1
3        1.891805 -1.264555      -1
4       -0.742754  2.443213      -1
...           ...       ...     ...
2216780 -0.976038  1.568022      -1
2216781 -0.294382 -0.241892      -1
2216782 -0.622989 -0.150585      -1
2216783  0.017930 -0.059278      -1
2216784 -0.362276 -0.282473      -1

[2216785 rows x 3 columns]

In [24]:
(data2['labels'] == -1).sum()

1373017

In [25]:
db2 = DBSCAN(eps=0.9, min_samples=9, metric='euclidean', n_jobs=4)

In [26]:
y_db2 = db2.fit_predict(data)

In [ ]:
labels2 = db2.labels_

In [ ]:
np.unique(labels2)

In [ ]:
# 在 db2 放大 eps , 減少 min_samples後 群集數反而加大了?

In [ ]:
(labels2 == -1).sum()
# 不過在 db2 被分為雜訊的點有確實變少了

In [27]:
db3 = DBSCAN(eps=1.2, min_samples=9, metric='euclidean')
y_db3 = db3.fit_predict(data)

In [28]:
labels3 = db3.labels_

In [29]:
(labels3 == -1).sum()

223286

In [31]:
np.unique(labels3)

array([   -1,     0,     1, ..., 12959, 12960, 12961], dtype=int64)